### PR TITLE
fix(typography): update typography for headings

### PR DESCRIPTION
**Pull request by gfellerph**
Update font weight and responsive size of headings and provide better typography examples in the demo app.

### CODE REVIEW

**Comment by gfellerph** [comment]
@swisspost/design, this PR can be reviewed at https://preview-115--swisspost-web-frontend.netlify.app/#/bootstrap-samples/typography.

**Comment by wueestd** [comment]
Not sure if we have even a even larger font on viewport >1280px, but not sure. do you know @rouvenpost?

**Review by rouvenpost — COMMENTED** [review]
Wenn i look at the Size at 1440 the H1 is 37.5 (see Screenshot)
But in Figma it is 48px on 1440... how does this 37.5 come in Place? The next Size to 37.4 would be 40px...
Screenshot 2022-06-27 at 13 18 04
930580-a27366d7-4760-4e4e-af2f-d94574c55d6c.png">

**Review by rouvenpost — APPROVED** [review]

**Review by rouvenpost — COMMENTED** [review]
approved

**Pull request merged**
